# Use root/example as user/password credentials
version: '3.1'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    container_name: "myapp-app"
    working_dir: "/app"
    volumes:
      - ./resuelve:/app:Z
    depends_on:
      - maria_db
    links:
      - maria_db

  maria_db:
    image: mariadb:10.5.5
    container_name: "myapp-mariadb"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - ./mariadb/data:/var/lib/mysql:z
    ports:
    - 3306:3306
